apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-pv-volume
  labels:
    type: local
spec:
  storageClassName: file
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mac/go/files"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pv-claim
spec:
  storageClassName: file
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
